name: RankUp
main: RankUp\MainRankUp
version: 1.4
api: [3.12.0]

load: POSTWORLD
author: ecoron
description: rankup a player as vote reward, or after time playing on server
website: https://github.com/ecoron/RankUp
commands:
    voteranks:
        description: rankup a player as vote reward
        usage: "/vr"
        aliases: [vr, voteranks, vote]
        permission: voteranks.command
    timeranks:
        description: check time to play for next rank
        usage: "/tr"
        aliases: [tr, timeranks]
        permission: timeranks.command
    jobranks:
        description: list/choose jobranks
        usage: "/job [list/start/stop] <jobrank>"
        aliases: [job, jobranks, jr]
        permission: jobranks.command
permissions:
    voteranks.command:
        description: "rankup a player as vote reward"
        default: true
    timeranks.command:
        description: "check time to play for next rank"
        default: true
    jobranks.command:
        description: "list or choose jobranks"
        default: true
